add resetOnIdle method + timer 60sec
SlovakNationalGallery/stex-reader pull request #4
Opened 2024-06-27 11:53 UTC by igor-kamil

2024-07-03 11:27 UTC, FrantisekMichalSebestyen requested changes

2024-07-03 11:27 UTC, FrantisekMichalSebestyen commented on assets/css/main.css
> +  .allow-pinch-zoom {
is this needed?

2024-07-03 11:27 UTC, FrantisekMichalSebestyen commented on pages/publication/[id].vue
> +          <div class="h-[650px] allow-pinch-zoom">
is this needed?

2024-08-20 14:21 UTC, igor-kamil commented on assets/css/main.css
> +  .allow-pinch-zoom {
already removed in https://github.com/SlovakNationalGallery/stex-reader/pull/6

2024-08-20 14:21 UTC, igor-kamil commented on pages/publication/[id].vue
> +          <div class="h-[650px] allow-pinch-zoom">
no :D

2024-08-20 14:22 UTC, FrantisekMichalSebestyen approved these changes

2024-08-20 14:24 UTC, merged